import { createClient } from '@supabase/supabase-js';
import { NextRequest, NextResponse } from 'next/server';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

// GET /api/rfq - List purchase requests (RFQs)
export async function GET(request: NextRequest) {
  try {
    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const { searchParams } = new URL(request.url);

    const page = parseInt(searchParams.get('page') || '1');
    const limit = Math.min(parseInt(searchParams.get('limit') || '20'), 100);
    const offset = (page - 1) * limit;

    // Get user info from headers
    const userId = request.headers.get('x-user-id');
    const userRole = request.headers.get('x-user-role');

    // Override with query param if provided
    const buyerId = searchParams.get('buyer_id') || userId;
    const status = searchParams.get('status');
    const categoryId = searchParams.get('category_id');

    let query = supabase
      .from('purchase_requests')
      .select('*, categories!category_id(name_en, name_ar), profiles!buyer_id(full_name_en, company_name, country)', { count: 'exact' })
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    // Role-based filtering
    if (userRole === 'gulf_buyer' && buyerId) {
      query = query.eq('buyer_id', buyerId);
    } else if (userRole === 'chinese_supplier') {
      // Suppliers see all open RFQs
      query = query.in('status', ['open', 'receiving_quotes']);
    } else if (userRole === 'admin') {
      // Admins see all (no filter)
    }

    if (status) {
      query = query.eq('status', status);
    } else if (userRole !== 'chinese_supplier') {
      // Default status filter (except for suppliers who already have it)
      query = query.in('status', ['open', 'receiving_quotes', 'evaluating']);
    }

    if (categoryId) {
      query = query.eq('category_id', categoryId);
    }

    const { data, error, count } = await query;

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      data: data || [],
      meta: {
        page,
        limit,
        total: count || 0,
        totalPages: Math.ceil((count || 0) / limit)
      },
    });
  } catch (error) {
    console.error('RFQ list error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/rfq - Create a new RFQ
export async function POST(request: NextRequest) {
  try {
    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const body = await request.json();

    const {
      buyerId, title, productName, categoryId, description, specifications,
      quantity, unitOfMeasure, targetPrice, maxBudget, currency,
      requiredCertifications, preferredIncoterm, preferredPaymentTerms, preferredOrigin,
      deliveryAddress, destinationPort, requiredDeliveryDate,
      referenceImages, referenceDocuments,
    } = body;

    if (!buyerId || !title || !productName || !quantity) {
      return NextResponse.json(
        { error: 'Missing required fields: buyerId, title, productName, quantity' },
        { status: 400 }
      );
    }

    const { data, error } = await supabase
      .from('purchase_requests')
      .insert({
        reference_number: '', // Will be auto-generated by trigger
        buyer_id: buyerId,
        title,
        product_name: productName,
        category_id: categoryId || null,
        description: description || null,
        specifications: specifications || [],
        quantity,
        unit_of_measure: unitOfMeasure || 'piece',
        target_price: targetPrice || null,
        max_budget: maxBudget || null,
        currency: currency || 'USD',
        required_certifications: requiredCertifications || null,
        preferred_incoterm: preferredIncoterm || null,
        preferred_payment_terms: preferredPaymentTerms || null,
        preferred_origin: preferredOrigin || null,
        delivery_address: deliveryAddress || null,
        destination_port: destinationPort || null,
        required_delivery_date: requiredDeliveryDate || null,
        reference_images: referenceImages || null,
        reference_documents: referenceDocuments || null,
        status: 'open',
        expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days
      })
      .select()
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({ rfq: data }, { status: 201 });
  } catch (error) {
    console.error('RFQ create error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
