import {
  User,
  Company,
  BuyerProfile,
  SupplierProfile,
  ManufacturerProfile,
  Product,
  PurchaseRequest,
  Quotation,
  Deal,
  LC,
  LG,
  Shipment,
  QualityJourney,
  Partnership,
  CustomsClearance,
  UserRole,
  CompanyRole,
  AccountType,
  DealStage,
  LCStatus,
  LGStatus,
  LCType,
  LGType,
  PaymentTerms,
  ShipmentStatus,
  ShipmentType,
  QualityStage,
  InspectionResult,
  WorkflowStatus,
  Country,
  Currency,
  Incoterm,
} from '../types';

// ============================================================================
// DEMO USERS
// ============================================================================

export const DEMO_USERS: User[] = [
  // Saudi Arabia - Al-Rajhi Trading Company
  {
    id: 'user-001',
    email: 'ahmed.alrajhi@alrajhi-trading.sa',
    phone: '+966123456789',
    firstName: 'Ahmed',
    lastName: 'Al-Rajhi',
    role: UserRole.MANAGER,
    companyId: 'company-001',
    department: 'Procurement',
    status: 'active',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'user-002',
    email: 'fatima.albishi@alrajhi-trading.sa',
    phone: '+966123456790',
    firstName: 'Fatima',
    lastName: 'Al-Bishi',
    role: UserRole.EMPLOYEE,
    companyId: 'company-001',
    department: 'Procurement',
    status: 'active',
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'user-003',
    email: 'mohammad.alshammari@alrajhi-trading.sa',
    phone: '+966123456791',
    firstName: 'Mohammad',
    lastName: 'Al-Shammari',
    role: UserRole.EXECUTIVE,
    companyId: 'company-001',
    department: 'Executive',
    status: 'active',
    createdAt: new Date('2022-12-01'),
    updatedAt: new Date('2024-03-20'),
  },

  // UAE - Emirates Steel Traders
  {
    id: 'user-004',
    email: 'rashid.almaktoum@emirates-steel.ae',
    phone: '+971456789012',
    firstName: 'Rashid',
    lastName: 'Al-Maktoum',
    role: UserRole.BUYER,
    companyId: 'company-002',
    department: 'Procurement',
    status: 'active',
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2024-03-20'),
  },

  // China - Zhejiang Steel Manufacturing
  {
    id: 'user-005',
    email: 'wei.zhang@zhejiang-steel.cn',
    phone: '+8613812345678',
    firstName: 'Wei',
    lastName: 'Zhang',
    role: UserRole.SUPPLIER,
    companyId: 'company-003',
    department: 'Sales',
    status: 'active',
    createdAt: new Date('2023-01-10'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'user-006',
    email: 'li.wang@zhejiang-steel.cn',
    phone: '+8613912345678',
    firstName: 'Li',
    lastName: 'Wang',
    role: UserRole.MANAGER,
    companyId: 'company-003',
    department: 'Operations',
    status: 'active',
    createdAt: new Date('2023-02-05'),
    updatedAt: new Date('2024-03-20'),
  },

  // Saudi Arabia - Riyada Electronics Manufacturing
  {
    id: 'user-007',
    email: 'khalid.alarifi@riyada-electronics.sa',
    phone: '+966512345678',
    firstName: 'Khalid',
    lastName: 'Al-Arifi',
    role: UserRole.MANUFACTURER,
    companyId: 'company-007',
    department: 'Production',
    status: 'active',
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2024-03-20'),
  },

  // Kuwait - Gulf Star Electronics
  {
    id: 'user-008',
    email: 'nabeel.almutairi@gulfstar.kw',
    phone: '+96599876543',
    firstName: 'Nabeel',
    lastName: 'Al-Mutairi',
    role: UserRole.BUYER,
    companyId: 'company-004',
    department: 'Procurement',
    status: 'active',
    createdAt: new Date('2023-04-15'),
    updatedAt: new Date('2024-03-20'),
  },
];

// ============================================================================
// DEMO COMPANIES
// ============================================================================

export const DEMO_COMPANIES: Company[] = [
  // BUYERS
  {
    id: 'company-001',
    nameEn: 'Al-Rajhi Trading Company',
    nameAr: 'شركة الراجحي للتجارة',
    companyRole: CompanyRole.BUYER,
    accountType: AccountType.PREMIUM,
    registrationNumber: '1010123456',
    taxId: 'SA-123456789',
    website: 'www.alrajhi-trading.sa',
    email: 'info@alrajhi-trading.sa',
    phone: '+966123456789',
    address: 'Al-Faisaliah Tower, Riyadh',
    country: Country.SAUDI_ARABIA,
    city: 'Riyadh',
    sector: 'Steel & Metals Trading',
    employees: 250,
    certifications: ['ISO9001', 'SASO'],
    createdAt: new Date('2020-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'company-002',
    nameEn: 'Emirates Steel Traders',
    nameAr: 'تجار الفولاذ الإماراتية',
    companyRole: CompanyRole.BUYER,
    accountType: AccountType.ENTERPRISE,
    registrationNumber: '1234567890123',
    taxId: 'AE-987654321',
    website: 'www.emirates-steel.ae',
    email: 'info@emirates-steel.ae',
    phone: '+971456789012',
    address: 'Dubai Investment Park, Dubai',
    country: Country.UAE,
    city: 'Dubai',
    sector: 'Steel & Metals Trading',
    employees: 180,
    certifications: ['ISO9001', 'CE'],
    createdAt: new Date('2019-06-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'company-004',
    nameEn: 'Gulf Star Electronics',
    nameAr: 'نجم الخليج للإلكترونيات',
    companyRole: CompanyRole.BUYER,
    accountType: AccountType.ENTERPRISE,
    registrationNumber: 'KW-1122334455',
    taxId: 'KW-555666777',
    website: 'www.gulfstar-electronics.kw',
    email: 'info@gulfstar.kw',
    phone: '+96599876543',
    address: 'Shuwaikh Industrial Area, Kuwait City',
    country: Country.KUWAIT,
    city: 'Kuwait City',
    sector: 'Electronics & Components',
    employees: 120,
    certifications: ['ISO9001', 'IATF'],
    createdAt: new Date('2020-03-10'),
    updatedAt: new Date('2024-03-20'),
  },

  // SUPPLIERS
  {
    id: 'company-003',
    nameEn: 'Zhejiang Steel Manufacturing Co., Ltd.',
    nameAr: 'شركة تصنيع الفولاذ تشجيانج',
    companyRole: CompanyRole.SUPPLIER,
    accountType: AccountType.PREMIUM,
    registrationNumber: '330000000123456',
    taxId: 'CN-987654',
    website: 'www.zhejiang-steel.cn',
    email: 'sales@zhejiang-steel.cn',
    phone: '+8657123456789',
    address: 'Hangzhou, Zhejiang Province',
    country: Country.CHINA,
    city: 'Hangzhou',
    sector: 'Steel & Metals Manufacturing',
    employees: 450,
    certifications: ['ISO9001', 'ISO14001'],
    createdAt: new Date('2018-05-01'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'company-005',
    nameEn: 'Shanghai Electronics Components Ltd.',
    nameAr: 'شركة مكونات الإلكترونيات شنغهاي',
    companyRole: CompanyRole.SUPPLIER,
    accountType: AccountType.PREMIUM,
    registrationNumber: '310000000654321',
    taxId: 'CN-123456',
    website: 'www.shanghai-electronics.cn',
    email: 'export@shanghai-electronics.cn',
    phone: '+862156789012',
    address: 'Pudong, Shanghai',
    country: Country.CHINA,
    city: 'Shanghai',
    sector: 'Electronics & Components',
    employees: 380,
    certifications: ['ISO9001', 'IATF', 'CE'],
    createdAt: new Date('2017-08-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'company-006',
    nameEn: 'Jiangsu Solar Panel Manufacturing',
    nameAr: 'تصنيع الألواح الشمسية جيانغسو',
    companyRole: CompanyRole.SUPPLIER,
    accountType: AccountType.ENTERPRISE,
    registrationNumber: '320000000789456',
    taxId: 'CN-789456',
    website: 'www.jiangsu-solar.cn',
    email: 'sales@jiangsu-solar.cn',
    phone: '+862789012345',
    address: 'Taizhou, Jiangsu Province',
    country: Country.CHINA,
    city: 'Taizhou',
    sector: 'Solar & Renewable Energy',
    employees: 320,
    certifications: ['ISO9001', 'ISO45001', 'CE'],
    createdAt: new Date('2019-02-10'),
    updatedAt: new Date('2024-03-20'),
  },

  // MANUFACTURERS
  {
    id: 'company-007',
    nameEn: 'Riyada Electronics Manufacturing',
    nameAr: 'شركة ريادة لتصنيع الإلكترونيات',
    companyRole: CompanyRole.MANUFACTURER,
    accountType: AccountType.ENTERPRISE,
    registrationNumber: '1050123456',
    taxId: 'SA-444555666',
    website: 'www.riyada-electronics.sa',
    email: 'info@riyada-electronics.sa',
    phone: '+966512345678',
    address: 'MODON Industrial City, Riyadh',
    country: Country.SAUDI_ARABIA,
    city: 'Riyadh',
    sector: 'Electronics Manufacturing',
    employees: 280,
    certifications: ['ISO9001', 'ISO45001', 'IATF'],
    createdAt: new Date('2021-04-01'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'company-008',
    nameEn: 'Emirates Manufacturing Solutions',
    nameAr: 'حلول الإمارات للتصنيع',
    companyRole: CompanyRole.MANUFACTURER,
    accountType: AccountType.ENTERPRISE,
    registrationNumber: '1234567890456',
    taxId: 'AE-111222333',
    website: 'www.emirates-manufacturing.ae',
    email: 'production@emirates-manufacturing.ae',
    phone: '+971234567890',
    address: 'Jebel Ali Free Zone, Dubai',
    country: Country.UAE,
    city: 'Dubai',
    sector: 'Industrial Equipment Manufacturing',
    employees: 220,
    certifications: ['ISO9001', 'ISO14001', 'CE'],
    createdAt: new Date('2020-07-15'),
    updatedAt: new Date('2024-03-20'),
  },
];

// ============================================================================
// DEMO BUYER PROFILES
// ============================================================================

export const DEMO_BUYER_PROFILES: BuyerProfile[] = [
  {
    id: 'buyer-001',
    companyId: 'company-001',
    industry: 'Steel & Metals Trading',
    annualBudget: 50000000,
    purchasingCapacity: 5000000,
    preferredTerms: [PaymentTerms.LC, PaymentTerms.NET_60],
    tradingHistory: 15,
    certifications: ['ISO9001', 'SASO'],
    rating: 4.8,
    reviewCount: 127,
  },
  {
    id: 'buyer-002',
    companyId: 'company-002',
    industry: 'Steel & Metals Trading',
    annualBudget: 35000000,
    purchasingCapacity: 3500000,
    preferredTerms: [PaymentTerms.LC, PaymentTerms.NET_90],
    tradingHistory: 12,
    certifications: ['ISO9001', 'CE'],
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: 'buyer-003',
    companyId: 'company-004',
    industry: 'Electronics & Components',
    annualBudget: 25000000,
    purchasingCapacity: 2500000,
    preferredTerms: [PaymentTerms.LC, PaymentTerms.NET_60],
    tradingHistory: 8,
    certifications: ['ISO9001', 'IATF'],
    rating: 4.7,
    reviewCount: 76,
  },
];

// ============================================================================
// DEMO SUPPLIER PROFILES
// ============================================================================

export const DEMO_SUPPLIER_PROFILES: SupplierProfile[] = [
  {
    id: 'supplier-001',
    companyId: 'company-003',
    minOrderQuantity: 5000,
    leadTime: 35,
    productCategories: ['Flat-rolled Steel', 'Stainless Steel', 'Carbon Steel'],
    certifications: ['ISO9001', 'ISO14001'],
    qualityRating: 4.8,
    deliveryRating: 4.7,
    communicationRating: 4.9,
    totalOrders: 287,
    successRate: 98.6,
    exportExperience: 18,
  },
  {
    id: 'supplier-002',
    companyId: 'company-005',
    minOrderQuantity: 1000,
    leadTime: 28,
    productCategories: ['Semiconductors', 'Capacitors', 'Resistors', 'Circuit Boards'],
    certifications: ['ISO9001', 'IATF', 'CE'],
    qualityRating: 4.9,
    deliveryRating: 4.8,
    communicationRating: 4.8,
    totalOrders: 456,
    successRate: 99.1,
    exportExperience: 22,
  },
  {
    id: 'supplier-003',
    companyId: 'company-006',
    minOrderQuantity: 50,
    leadTime: 42,
    productCategories: ['Solar Panels', 'Inverters', 'Solar Cables'],
    certifications: ['ISO9001', 'ISO45001', 'CE'],
    qualityRating: 4.7,
    deliveryRating: 4.6,
    communicationRating: 4.7,
    totalOrders: 178,
    successRate: 97.8,
    exportExperience: 8,
  },
];

// ============================================================================
// DEMO MANUFACTURER PROFILES
// ============================================================================

export const DEMO_MANUFACTURER_PROFILES: ManufacturerProfile[] = [
  {
    id: 'mfg-001',
    companyId: 'company-007',
    factorySize: 'large',
    employees: 280,
    productionCapacity: 500000,
    leadTime: 45,
    certifications: ['ISO9001', 'ISO45001', 'IATF'],
    specializations: ['PCB Assembly', 'Component Integration', 'Testing'],
    laborCompliance: true,
    environmentalCertification: true,
    qualityManagement: 'ISO9001:2015',
    customCapability: true,
  },
  {
    id: 'mfg-002',
    companyId: 'company-008',
    factorySize: 'large',
    employees: 220,
    productionCapacity: 300000,
    leadTime: 50,
    certifications: ['ISO9001', 'ISO14001', 'CE'],
    specializations: ['Metal Fabrication', 'Assembly', 'Finishing'],
    laborCompliance: true,
    environmentalCertification: true,
    qualityManagement: 'ISO9001:2015',
    customCapability: true,
  },
];

// ============================================================================
// DEMO PRODUCTS
// ============================================================================

export const DEMO_PRODUCTS: Product[] = [
  // Steel Products
  {
    id: 'product-001',
    supplierId: 'company-003',
    nameEn: 'Hot Rolled Coil (HRC) Steel',
    nameAr: 'ملف الفولاذ المسحوب على البارد',
    sku: 'HRC-2024-001',
    categoryEn: 'Steel & Metals',
    categoryAr: 'الفولاذ والمعادن',
    description: 'High-quality hot rolled coil steel suitable for automotive and construction industries.',
    specification: 'Thickness: 3-12mm, Width: 1000-1500mm, Tensile Strength: 400-550 MPa',
    unitPrice: 580,
    currency: Currency.USD,
    minOrderQuantity: 5000,
    packagingType: 'Coil on Pallet',
    unitOfMeasure: 'MT (Metric Ton)',
    leadTime: 35,
    moq: 5000,
    certifications: ['ISO9001', 'ISO14001'],
    createdAt: new Date('2023-01-15'),
  },
  // Electronics
  {
    id: 'product-002',
    supplierId: 'company-005',
    nameEn: 'Industrial PCB Assembly',
    nameAr: 'تجميع لوحة الدوائس الإلكترونية',
    sku: 'PCB-ASMBLY-2024',
    categoryEn: 'Electronics',
    categoryAr: 'الإلكترونيات',
    description: 'Professional PCB assembly services with component soldering and quality testing.',
    specification: '2-layer to 10-layer PCB, Lead-free soldering, RoHS compliant',
    unitPrice: 45,
    currency: Currency.USD,
    minOrderQuantity: 1000,
    packagingType: 'Box',
    unitOfMeasure: 'Unit',
    leadTime: 28,
    moq: 1000,
    certifications: ['IATF', 'CE', 'ISO9001'],
    createdAt: new Date('2023-02-20'),
  },
  // Solar Panels
  {
    id: 'product-003',
    supplierId: 'company-006',
    nameEn: 'Monocrystalline Solar Panel 400W',
    nameAr: 'لوحة شمسية أحادية البلورة 400 واط',
    sku: 'SOLAR-400W-2024',
    categoryEn: 'Solar & Renewable Energy',
    categoryAr: 'الطاقة الشمسية والمتجددة',
    description: 'High efficiency monocrystalline solar panel with excellent light absorption.',
    specification: '400W, 22.5% efficiency, 1956x992x40mm, IP67 rated',
    unitPrice: 285,
    currency: Currency.USD,
    minOrderQuantity: 50,
    packagingType: 'Pallet',
    unitOfMeasure: 'Unit',
    leadTime: 42,
    moq: 50,
    certifications: ['CE', 'TUV', 'ISO9001'],
    createdAt: new Date('2023-03-10'),
  },
  // Packaging
  {
    id: 'product-004',
    supplierId: 'company-005',
    nameEn: 'Corrugated Cardboard Boxes',
    nameAr: 'صناديق الكرتون المموج',
    sku: 'BOX-CORRUGATED-2024',
    categoryEn: 'Packaging & Materials',
    categoryAr: 'التغليف والمواد',
    description: 'Custom printed corrugated boxes for shipping and storage.',
    specification: 'Various sizes, custom printing, water resistant, eco-friendly',
    unitPrice: 0.85,
    currency: Currency.USD,
    minOrderQuantity: 10000,
    packagingType: 'Flat',
    unitOfMeasure: 'Unit',
    leadTime: 21,
    moq: 10000,
    certifications: ['FSC', 'ISO9001'],
    createdAt: new Date('2023-04-05'),
  },
  // Pharmaceuticals
  {
    id: 'product-005',
    supplierId: 'company-005',
    nameEn: 'Pharmaceutical Capsules Size 00',
    nameAr: 'كبسولات صيدلانية حجم 00',
    sku: 'PHARM-CAPS-00-2024',
    categoryEn: 'Pharmaceuticals',
    categoryAr: 'الأدوية',
    description: 'Empty pharmaceutical capsules for medicine production.',
    specification: 'Size 00, Gelatin-based, DIN/EP/USP compliant, GMO-free',
    unitPrice: 0.02,
    currency: Currency.USD,
    minOrderQuantity: 100000,
    packagingType: 'Bulk Bag',
    unitOfMeasure: 'Unit',
    leadTime: 30,
    moq: 100000,
    certifications: ['ISO9001', 'GMP'],
    createdAt: new Date('2023-05-12'),
  },
];

// ============================================================================
// DEMO PURCHASE REQUESTS
// ============================================================================

export const DEMO_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'pr-001',
    referenceNumber: 'PR-2024-001',
    buyerId: 'user-001',
    productId: 'product-001',
    quantity: 10000,
    unitOfMeasure: 'MT',
    requiredDeliveryDate: new Date('2024-06-15'),
    budget: 5800000,
    currency: Currency.USD,
    status: WorkflowStatus.APPROVED,
    quotations: ['quote-001'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'pr-002',
    referenceNumber: 'PR-2024-002',
    buyerId: 'user-004',
    productId: 'product-003',
    quantity: 500,
    unitOfMeasure: 'Unit',
    requiredDeliveryDate: new Date('2024-07-01'),
    budget: 145000,
    currency: Currency.USD,
    status: WorkflowStatus.APPROVED,
    quotations: ['quote-002'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-20'),
  },
];

// ============================================================================
// DEMO QUOTATIONS
// ============================================================================

export const DEMO_QUOTATIONS: Quotation[] = [
  {
    id: 'quote-001',
    referenceNumber: 'QT-2024-0001',
    purchaseRequestId: 'pr-001',
    supplierId: 'company-003',
    productId: 'product-001',
    quantity: 10000,
    unitPrice: 580,
    currency: Currency.USD,
    totalPrice: 5800000,
    incoterm: Incoterm.CIF,
    paymentTerms: PaymentTerms.LC,
    leadTime: 35,
    validUntil: new Date('2024-04-01'),
    status: WorkflowStatus.APPROVED,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'quote-002',
    referenceNumber: 'QT-2024-0002',
    purchaseRequestId: 'pr-002',
    supplierId: 'company-006',
    productId: 'product-003',
    quantity: 500,
    unitPrice: 285,
    currency: Currency.USD,
    totalPrice: 142500,
    incoterm: Incoterm.FOB,
    paymentTerms: PaymentTerms.ADVANCE_DEPOSIT,
    leadTime: 42,
    validUntil: new Date('2024-04-15'),
    status: WorkflowStatus.APPROVED,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-20'),
  },
];

// ============================================================================
// DEMO DEALS
// ============================================================================

export const DEMO_DEALS: Deal[] = [
  {
    id: 'deal-001',
    referenceNumber: 'DEAL-2024-0001',
    buyerId: 'user-001',
    supplierId: 'company-003',
    productId: 'product-001',
    quantity: 10000,
    unitPrice: 580,
    totalValue: 5800000,
    currency: Currency.USD,
    incoterm: Incoterm.CIF,
    paymentTerms: PaymentTerms.LC,
    stage: DealStage.GOODS_IN_TRANSIT,
    expectedDeliveryDate: new Date('2024-06-15'),
    shippingPort: 'CNSHA',
    destinationPort: 'SAWHA',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'deal-002',
    referenceNumber: 'DEAL-2024-0002',
    buyerId: 'user-004',
    supplierId: 'company-006',
    productId: 'product-003',
    quantity: 500,
    unitPrice: 285,
    totalValue: 142500,
    currency: Currency.USD,
    incoterm: Incoterm.FOB,
    paymentTerms: PaymentTerms.ADVANCE_DEPOSIT,
    stage: DealStage.PRODUCTION_INSPECTION,
    expectedDeliveryDate: new Date('2024-07-01'),
    shippingPort: 'CNSZX',
    destinationPort: 'AEJEB',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'deal-003',
    referenceNumber: 'DEAL-2024-0003',
    buyerId: 'user-008',
    supplierId: 'company-005',
    productId: 'product-002',
    quantity: 5000,
    unitPrice: 45,
    totalValue: 225000,
    currency: Currency.USD,
    incoterm: Incoterm.CIF,
    paymentTerms: PaymentTerms.NET_60,
    stage: DealStage.QUOTATION_ACCEPTED,
    expectedDeliveryDate: new Date('2024-05-20'),
    shippingPort: 'CNSHA',
    destinationPort: 'KWPCA',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-10'),
  },
];

// ============================================================================
// DEMO LETTERS OF CREDIT
// ============================================================================

export const DEMO_LCS: LC[] = [
  {
    id: 'lc-001',
    referenceNumber: 'LC-2024-0001',
    dealId: 'deal-001',
    buyerId: 'user-001',
    supplierId: 'company-003',
    bankId: 'bank-001',
    type: LCType.IRREVOCABLE,
    amount: 5800000,
    currency: Currency.USD,
    issueDate: new Date('2024-03-10'),
    expiryDate: new Date('2024-09-10'),
    shipmentsRequired: 1,
    description: 'LC for hot rolled coil steel shipment',
    documentsRequired: [
      'Bill of Lading',
      'Commercial Invoice',
      'Packing List',
      'Certificate of Origin',
      'Inspection Certificate',
    ],
    status: LCStatus.ISSUED,
    amountUsed: 5800000,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 'lc-002',
    referenceNumber: 'LC-2024-0002',
    dealId: 'deal-002',
    buyerId: 'user-004',
    supplierId: 'company-006',
    bankId: 'bank-002',
    type: LCType.IRREVOCABLE,
    amount: 142500,
    currency: Currency.USD,
    issueDate: new Date('2024-03-15'),
    expiryDate: new Date('2024-09-15'),
    shipmentsRequired: 1,
    description: 'LC for solar panels shipment',
    documentsRequired: ['Bill of Lading', 'Commercial Invoice', 'Packing List', 'Certificate of Origin'],
    status: LCStatus.APPROVED,
    amountUsed: 0,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-17'),
  },
];

// ============================================================================
// DEMO LETTERS OF GUARANTEE
// ============================================================================

export const DEMO_LGS: LG[] = [
  {
    id: 'lg-001',
    referenceNumber: 'LG-2024-0001',
    dealId: 'deal-002',
    requesterId: 'user-004',
    bankId: 'bank-002',
    type: LGType.PERFORMANCE_BOND,
    amount: 50000,
    currency: Currency.USD,
    issueDate: new Date('2024-02-20'),
    expiryDate: new Date('2024-12-20'),
    claimCondition: 'Non-performance of manufacturing obligations',
    beneficiary: 'Emirates Steel Traders (company-002)',
    status: LGStatus.ISSUED,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-22'),
  },
];

// ============================================================================
// DEMO SHIPMENTS
// ============================================================================

export const DEMO_SHIPMENTS: Shipment[] = [
  {
    id: 'shipment-001',
    referenceNumber: 'SHIP-2024-0001',
    dealId: 'deal-001',
    supplierId: 'company-003',
    buyerId: 'user-001',
    type: ShipmentType.SEA,
    carrierId: 'cosco',
    carrierName: 'COSCO Shipping',
    originPort: 'CNSHA',
    destinationPort: 'SAWHA',
    departureDate: new Date('2024-03-15'),
    expectedArrivalDate: new Date('2024-05-15'),
    status: ShipmentStatus.IN_TRANSIT,
    containerNumber: 'COSU1234567',
    blNumber: 'BL2024001',
    packagesCount: 150,
    totalWeight: 10000,
    totalVolume: 500,
    insurance: true,
    insuranceValue: 5800000,
    insuranceProvider: 'P&I Club',
    trackingUrl: 'https://tracking.cosco.com/bl/BL2024001',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-20'),
  },
];

// ============================================================================
// DEMO QUALITY JOURNEYS
// ============================================================================

export const DEMO_QUALITY_JOURNEYS: QualityJourney[] = [
  {
    id: 'qj-001',
    dealId: 'deal-001',
    startDate: new Date('2024-03-01'),
    status: WorkflowStatus.IN_PROGRESS,
    stages: [
      {
        id: 'qi-001',
        stageId: 'stage-001',
        stage: QualityStage.PRE_PRODUCTION,
        dealId: 'deal-001',
        inspectorId: 'user-005',
        result: InspectionResult.PASS,
        defectRate: 0,
        notes: 'Raw materials approved',
        photos: [],
        certifications: ['ISO9001'],
        completedAt: new Date('2024-03-02'),
      },
      {
        id: 'qi-002',
        stageId: 'stage-002',
        stage: QualityStage.MATERIAL_CHECK,
        dealId: 'deal-001',
        inspectorId: 'user-005',
        result: InspectionResult.PASS,
        defectRate: 0,
        notes: 'Material composition verified',
        photos: [],
        certifications: ['ISO9001'],
        completedAt: new Date('2024-03-03'),
      },
      {
        id: 'qi-003',
        stageId: 'stage-003',
        stage: QualityStage.FIRST_ARTICLE_INSPECTION,
        dealId: 'deal-001',
        inspectorId: 'user-005',
        result: InspectionResult.PASS,
        defectRate: 0,
        notes: 'First article samples approved',
        photos: [],
        certifications: ['ISO9001'],
        completedAt: new Date('2024-03-05'),
      },
    ],
    overallResult: InspectionResult.PASS,
    summary: 'Quality inspections progressing well. All stages passing so far.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-18'),
  },
];

// ============================================================================
// DEMO CUSTOMS CLEARANCES
// ============================================================================

export const DEMO_CUSTOMS_CLEARANCES: CustomsClearance[] = [
  {
    id: 'cc-001',
    referenceNumber: 'CC-2024-0001',
    shipmentId: 'shipment-001',
    importerId: 'user-001',
    importCountry: Country.SAUDI_ARABIA,
    hsCode: '7225',
    declaredValue: 5800000,
    currency: Currency.USD,
    dutyRate: 5.0,
    estimatedDuty: 290000,
    estimatedVAT: 1635000,
    status: WorkflowStatus.PENDING,
    documentsSubmitted: ['Invoice', 'Packing List', 'Certificate of Origin'],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
];

// ============================================================================
// DEMO PARTNERSHIPS
// ============================================================================

export const DEMO_PARTNERSHIPS: Partnership[] = [
  {
    id: 'partnership-001',
    referenceNumber: 'PART-2024-0001',
    initiatorId: 'company-003',
    partnerId: 'company-007',
    status: PartnershipStatus.AGREEMENT_SIGNED,
    partnershipType: 'MANUFACTURING',
    description: 'Manufacturing partnership for specialized steel processing',
    terms: 'Exclusive supply agreement with quarterly reviews',
    startDate: new Date('2024-01-15'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'partnership-002',
    referenceNumber: 'PART-2024-0002',
    initiatorId: 'company-006',
    partnerId: 'company-008',
    status: PartnershipStatus.UNDER_DISCUSSION,
    partnershipType: 'LABOR_LENDING',
    description: 'Labor training and technology transfer agreement',
    terms: 'Technology transfer for solar panel assembly techniques',
    trainingDirections: ['MANUFACTURING_TECHNIQUES', 'QUALITY_CONTROL'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-18'),
  },
];
